In [15]:
import numpy as np

In [16]:
a = np.arange(4)
a2 = a [np.newaxis, :]
a2.shape


(1, 4)

In [17]:
b = np.array([1,2,3,4,])
b

array([1, 2, 3, 4])

In [18]:
type(a)

numpy.ndarray

In [20]:
#list of arrays
arr = np.array([[1,2,3],[4,5,6]])
type(arr)

numpy.ndarray

In [22]:
arr
# 2 - axis
# first axis has length 2
# second axis has length 3

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
# ecmaples of arrays
ar = np.zeros(3)
ar

array([0., 0., 0.])

In [24]:
# ecmaples of arrays
ar3 = np.ones(5)
ar3

array([1., 1., 1., 1., 1.])

In [25]:
are = np.empty(5)
are 

array([1., 1., 1., 1., 1.])

## one dimentional array is called Vector
## Two dimentional array is called Matrix
## 3d arrays are called tensor
## dimensions are called axis

In [ ]:
# practice session


In [27]:
test_arr = np.arange(5)
test_arr

array([0, 1, 2, 3, 4])

In [28]:
test_arr = np.arange(4,7)
test_arr

array([4, 5, 6])

In [29]:
test_arr = np.arange(4,21,2)
test_arr

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20])

In [31]:
test_arr = np.linspace(4,223,num=4)
test_arr

array([  4.,  77., 150., 223.])

In [37]:
#array with specific data type
i = np.ones(4,dtype=np.int16)
i

iy = np.ones(4,dtype=np.float32)
iy


ir = np.ones(4,dtype=np.float32)
ir


ei = np.ones(4,dtype=np.int8)
ei


array([1, 1, 1, 1], dtype=int8)

In [39]:
op = np.zeros((3,4))
op

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [44]:
# 3D Array

arry = np.arange(30).reshape(2,3,5)
arry

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])