# numpy adv course

In [4]:
import numpy as np
temp=np.array(["pakora","samosa","haleem","132"])
temp

array(['pakora', 'samosa', 'haleem', '132'], dtype='<U6')

In [5]:
import numpy as np
t=np.array([12,44,12,33,231,23.1])
t.mean()


59.18333333333334

In [6]:
o = np.ones(2)
o

array([1., 1.])

In [15]:
n = np.zeros(23)
n


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.])

h = np.arange(10,50,2)
h

In [17]:
np.linspace(0,100, num =4)  #4 equally spaced numbers between range from start to end

array([  0.        ,  33.33333333,  66.66666667, 100.        ])

In [18]:
# specify your data type
g = np.ones(50,dtype=np.int32)
g

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1])

In [19]:
# specify your data type
g = np.ones(50,dtype=np.float32)
g

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
      dtype=float32)

# Array functions

In [29]:
u= np.array([10,12,15,4,21,5,0.2])
u


array([10. , 12. , 15. ,  4. , 21. ,  5. ,  0.2])

In [30]:
u.sort()
u

array([ 0.2,  4. ,  5. , 10. , 12. , 15. , 21. ])

In [31]:
b = np.array([1,3,5,3,1,4.3])
b

array([1. , 3. , 5. , 3. , 1. , 4.3])

In [33]:
c=np.concatenate((u,b))
c

array([ 0.2,  4. ,  5. , 10. , 12. , 15. , 21. ,  1. ,  3. ,  5. ,  3. ,
        1. ,  4.3])

In [35]:
c.sort()
c

array([ 0.2,  1. ,  1. ,  3. ,  3. ,  4. ,  4.3,  5. ,  5. , 10. , 12. ,
       15. , 21. ])

In [36]:
#2-D Array

arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
arr2 = np.array([[3,4,5],[8,7,6]])
arr2


array([[3, 4, 5],
       [8, 7, 6]])

In [43]:
arrc = np.concatenate((arr,arr2))
arrc

array([[1, 2, 3],
       [4, 5, 6],
       [3, 4, 5],
       [8, 7, 6]])

In [44]:
arrc = np.concatenate((arr,arr2),axis = 0)
arrc

array([[1, 2, 3],
       [4, 5, 6],
       [3, 4, 5],
       [8, 7, 6]])

In [45]:
arrc = np.concatenate((arr,arr2),axis = 1)
arrc

array([[1, 2, 3, 3, 4, 5],
       [4, 5, 6, 8, 7, 6]])

In [46]:
arrc.ndim

2

In [47]:
arrg = np.array([[[1,2,3],[4,5,5]],
               [[1,2,3],[4,5,5]],
               [[1,2,3],[4,5,5]]])
arrg

array([[[1, 2, 3],
        [4, 5, 5]],

       [[1, 2, 3],
        [4, 5, 5]],

       [[1, 2, 3],
        [4, 5, 5]]])

In [49]:
arrg.ndim # number of dimensions


3

In [50]:
arrg.size  # number of elements

18

In [52]:
arrg.shape

(3, 2, 3)

In [55]:
a= np.arange(6)
a


array([0, 1, 2, 3, 4, 5])

In [56]:
a.reshape(2,3)  #should have same total elements

array([[0, 1, 2],
       [3, 4, 5]])

In [57]:
a.reshape(2,3,1) 

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [62]:

#reshape func
np.reshape(a, newshape=(6,1), order = 'C')

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [65]:
#convert 1 D to 2 D 
#rowwise
b = a[np.newaxis,:]
b

array([[0, 1, 2, 3, 4, 5]])

In [66]:
#convert 1 D to 2 D 
#colwise
b = a[:,np.newaxis]
b

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [68]:
b.sum()

15